// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cv11.EFCore;

#nullable disable

namespace cv11.Migrations
{
    [DbContext(typeof(Vyukacontext))]
    [Migration("20250423150215_NoveTabulkyPokus2")]
    partial class NoveTabulkyPokus2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cv11.EFCore.Hodnoceni", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumNarozeni")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZkratkaPredmet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Znamka")
                        .HasColumnType("float");

                    b.HasKey("StudentId");

                    b.ToTable("Hodnotenie");
                });

            modelBuilder.Entity("cv11.EFCore.Predmet", b =>
                {
                    b.Property<string>("Zkratka")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Znamka")
                        .HasColumnType("float");

                    b.HasKey("Zkratka");

                    b.ToTable("Predmety");
                });

            modelBuilder.Entity("cv11.EFCore.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumNarozeni")
                        .HasColumnType("datetime2");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prijmeni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("cv11.EFCore.StudentPredmet", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Zkratka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("StudentPredmet");
                });
#pragma warning restore 612, 618
        }
    }
}
